Traceback (most recent call last):
  File "train_lpcnet_parallel.py", line 125, in <module>
    init()
  File "/home/mindocr/.conda/envs/ssd_ms18/lib/python3.7/site-packages/mindspore/communication/management.py", line 146, in init
    init_hccl()
RuntimeError: Ascend error occurred, error message: EI0004: The ranktable is invalid,Reason:[Invalid ranktable format.]. Please check the configured ranktable.[/media/data1/xidian/xy/models/official/audio/LPCNet/hccl_8p.json]
        Solution: Try again with a valid cluster configuration in the ranktable file. Ensure that the configuration matches the operating environment.
        In [HcomInitByFile], value [/media/data1/xidian/xy/models/official/audio/LPCNet/hccl_8p.json] for parameter [rankTablePath] is invalid. Reason: The collective communication operator has an invalid argument. Reason[/media/data1/xidian/xy/models/official/audio/LPCNet/hccl_8p.json]

First error scene API: Init hccl graph adapter failed.

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ccsrc/plugin/device/ascend/hal/device/ascend_kernel_runtime.cc:363 Init
mindspore/ccsrc/plugin/device/ascend/hal/hccl_adapter/hccl_adapter.cc:408 InitKernelInfoStore


